Repository GSG-G11/Taskillo, pull requests merged in 2022-04, with the labels that each got.

#2 [Back-end] Create File Structure
  server/.eslintrc.json
  server/.gitignore
  server/app.ts
  server/controllers/auth/index.ts
  server/controllers/errors/index.ts
  server/controllers/index.ts
  server/controllers/projects/index.ts
  server/database/ quieres/build.ts
  server/database/config/build.sql
  server/database/config/build.ts
  server/database/config/connection.ts
  server/database/config/fakeData.sql
  server/index.ts
  server/middlewares/index.ts
  server/middlewares/setCookie.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/tsconfig.json
  server/utils/index.ts
  server/utils/serverSideValidation/index.ts
Labels: Approved

#10 Create database schema
  server/database/config/build.sql
Labels: back-end, Approved

#7 Create checkAuth Middleware
  server/controllers/auth/checkAuth.ts
  server/package.json
Labels: Awaiting Review, back-end

#18 Create signToken and verifyToken promise
  server/package-lock.json
  server/package.json
  server/tsconfig.json
  server/utils/index.ts
  server/utils/jwt/index.ts
  server/utils/jwt/signToken.d.ts
  server/utils/jwt/verifyToken.d.ts
Labels: Awaiting Review, back-end

#14 Create validation schema sign up form
  server/package-lock.json
  server/package.json
  server/utils/serverSideValidation/signUpSchema.ts
Labels: Awaiting Review, back-end

#17 Create validation schema signin form
  server/utils/index.ts
  server/utils/serverSideValidation/index.ts
  server/utils/validation/index.ts
  server/utils/validation/signInSchema.ts
  server/utils/validation/signUpSchema.ts
Labels: Awaiting Review, back-end

#19 Create build file
  package-lock.json
  package.json
  server/.eslintrc.json
  server/controllers/projects/index.ts
  server/database/ quieres/build.ts
  server/database/config/build.ts
  server/database/config/fakeData.sql
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/auth/checkAuth.ts
  server/src/controllers/auth/index.ts
  server/src/controllers/errors/index.ts
  server/src/controllers/index.ts
  server/src/controllers/projects/index.ts
  server/src/database/ quieres/build.ts
  server/src/database/config/build.sql
  server/src/database/config/build.ts
  server/src/database/config/connection.ts
  server/src/database/config/fakeData.sql
  server/src/index.ts
  server/src/middlewares/index.ts
  server/src/routes/index.ts
  server/src/utils/index.ts
  server/src/utils/jwt/index.ts
  server/src/utils/jwt/signToken.ts
  server/src/utils/jwt/verifyToken.ts
  server/src/utils/validation/index.ts
  server/src/utils/validation/signInSchema.ts
  server/src/utils/validation/signUpSchema.ts
  server/tsconfig.json
Labels: Awaiting Review, back-end

#20 Delete All Json File Out the server folder
  package-lock.json
  package.json
Labels: Awaiting Review

#23 Cloudinary middleware
  server/package-lock.json
  server/package.json
  server/src/middlewares/Cloudinary/index.ts
  server/src/middlewares/index.ts
Labels: Awaiting Review, back-end

#31 Edit validation signup form
  server/src/utils/validation/signUpSchema.ts
Labels: back-end, Approved

#24 Setup the server
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/user/index.ts
  server/src/controllers/user/login.ts
  server/src/database/ quieres/build.ts
  server/src/database/ quieres/checkEmailQuery.ts
  server/src/database/ quieres/index.ts
  server/src/index.ts
  server/src/routes/index.ts
Labels: Awaiting Review, back-end

#35 Edit Database Schema
  server/src/database/config/build.sql
Labels: back-end, Approved

#36 Create sendCode Middleware
  server/package-lock.json
  server/package.json
  server/src/controllers/auth/index.ts
  server/src/middlewares/checkAuth.ts
  server/src/utils/cloudinary/index.ts
  server/src/utils/verification/sendCode.ts
Labels: Awaiting Review, back-end

#37 Create verifyCode Middleware
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/utils/verification/verifyCode.ts
Labels: back-end, Approved
